FROM php:7.4.28-apache-buster

#Creacion de simplesaml
RUN mkdir -p /var/www/simplesaml

COPY . /var/www/simplesaml/
COPY ./000-default.conf  /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite 
RUN docker-php-ext-install mysqli
RUN service apache2 restart

EXPOSE 80
