apiVersion: v1
kind: Service
metadata:
  name: simplesaml
  labels:
    app: simplesaml
spec:
  selector:
   app: simplesaml
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30000
  selector:
    role: simplesaml
