apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplesaml
spec:
  selector:
   matchLabels:
    app: simplesaml
  replicas: 1
  template:
    metadata:
      labels:
        app: simplesaml
        role: simplesaml
    spec:
      containers:
        - name: simplesaml
          image: simplesaml:0.0.1       
          ports:
            - containerPort: 80
              name: simplesaml


