apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        role: demo
    spec:
      containers:
        - name: demo
          image: itzelmunguia/demo:latest
          ports:
            - containerPort: 80
              name: demo




---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
   app: demo
  type: LoadBalancer
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: demo



