---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  ROOT_PASSWORD: c2VndXJpZGFkLW1heGltYS1teXNxbA==


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-disk-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql2
  template:
    metadata:
      labels:
        app: mysql2
    spec:
      containers:
        - name: mysql2
          image: mysql:8.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-disk
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: ROOT_PASSWORD
      volumes:
        - name: mysql-disk
          persistentVolumeClaim:
            claimName: mysql-disk-data

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-services
spec:
  selector:
    app: mysql2
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
